application: comic-pull-db
module: batch
version: rgh
runtime: python27
instance_class: F1
api_version: 1
threadsafe: true

builtins:
- appstats: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /tasks/issues/.*
  script: tasks.issues.app
  login: admin
- url: /tasks/pulls/.*
  script: tasks.pulls.app
  login: admin
- url: /tasks/streams/.*
  script: tasks.streams.app
  login: admin
- url: /tasks/subscriptions/.*
  script: tasks.subscriptions.app
  login: admin
- url: /batch/subscriptions/.*
  script: tasks.subscriptions.app
- url: /tasks/volumes/.*
  script: tasks.volumes.app
  login: admin
- url: /batch/volumes/.*
  script: tasks.volumes.app
