application: comic-pull-db
module: api
version: live
runtime: python27
instance_class: F1
api_version: 1
threadsafe: true
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value

handlers:
- url: /api/issues/.*
  script: api.issues.app
- url: /api/pulls/.*
  script: api.pulls.app
- url: /api/subscriptions/.*
  script: api.subscriptions.app
- url: /api/volumes/.*
  script: api.volumes.app
